# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This code is generated by a guy looking at files under the /system folder on his phone.

# Prebuilt libraries that are needed to build open-source libraries

#
# WiFi & Bluetooth
#
PRODUCT_COPY_FILES += \
    vendor/samsung/i857/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/samsung/i857/proprietary/etc/wifi/wifi.conf:system/etc/wifi/wifi.conf \
    vendor/samsung/i857/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/samsung/i857/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \
    vendor/samsung/i857/proprietary/bin/wpa_supplicant:system/bin/wpa_supplicant \
	vendor/samsung/i857/proprietary/bin/btld:system/bin/btld \
	vendor/samsung/i857/proprietary/bin/BCM2070B0_002.001.032.0515.0561.hcd:system/bin/BCM2070B0_002.001.032.0515.0561.hcd 
	
